name: Extract, transform, and load
on:
  workflow_dispatch:

jobs:
  etl:
    name: "ETL"
    runs-on: ubuntu-latest
        
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 35000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
          postgresql db: calaccess_website
          postgresql user: postgres
          postgresql password: postgres
          
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Install pipenv
        run: pipx install pipenv

      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pipenv'

      - id: pipenv-install
        name: Install Python dependencies
        run: pipenv install --dev --python `which python`
        
      - name: Set Django settings
        run: cp project/settings_actions.py.template project/settings_local.py
        shell: bash

      - name: Migrate database
        run: pipenv run python -W ignore manage.py migrate;
        shell: bash
        env:
          PGPASSWORD: postgres

      - name: Load scraped data
        run: pipenv run python -W ignore manage.py loadcalaccessscrapeddata --verbosity=3;
        shell: bash
        env:
          PGPASSWORD: postgres

      - name: Update raw and processed data
        run: pipenv run python -W ignore manage.py updatedownloadswebsite --noinput --verbosity=3;
        shell: bash
        env:
          PGPASSWORD: postgres
          
      - uses: shallwefootball/s3-upload-action@master
        name: Upload processed files
        with:
          aws_key_id: ${{ secrets.CALACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.CALACCESS_SECRET_KEY}}
          aws_bucket: calaccess-data
          source_dir: 'data/processed'
          destination_dir: 'latest'
