name: Extract, transform, and load
on:
  workflow_dispatch:

jobs:
  etl:
    name: "ETL"
    runs-on: ubuntu-latest
        
    steps:
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
          postgresql db: calaccess_website
          postgresql user: postgres
          postgresql password: postgres
          
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Install pipenv
        run: pipx install pipenv

      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pipenv'

      - id: pipenv-install
        name: Install Python dependencies
        run: pipenv install --dev --python `which python`
