name: Tests
on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.9,]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Install GIS packages
        run: sudo apt-get install binutils libproj-dev gdal-bin

      - name: Set up PostGIS
        uses: huaxk/postgis-action@v1
        with:
          postgresql version: '11'
          postgresql db: calaccess_processed
          postgresql user: postgres
          postgresql password: postgres

      - name: Install pipenv
        run: pipx install pipenv

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pipenv'

      - id: pipenv-install
        name: Install Python dependencies
        run: pipenv install --dev --python `which python`

      - name: Test
        run: make test
        env:
          PGPASSWORD: postgres